# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170801_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('menu', 'order', 'name'), 'verbose_name': '\u043f\u0443\u043d\u043a\u0442 \u043c\u0435\u043d\u044e', 'verbose_name_plural': '\u043f\u0443\u043d\u043a\u0442\u044b \u043c\u0435\u043d\u044e'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '\u043c\u0435\u043d\u044e', 'verbose_name_plural': '\u043c\u0435\u043d\u044e'},
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
