# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170801_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
