# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20170801_1342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('menu', 'url')]),
        ),
    ]
