# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20170801_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '\u043f\u0443\u043d\u043a\u0442 \u043c\u0435\u043d\u044e', 'verbose_name_plural': '\u043f\u0443\u043d\u043a\u0442\u044b \u043c\u0435\u043d\u044e'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
        migrations.AddField(
            model_name='menu',
            name='depth',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.Item'),
        ),
    ]
