# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20170803_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='level',
        ),
    ]
